import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
title: {
    template: "%s - Arbree Commerce Online Store", 
    default: "Arbree Commerce", 
  },
  description: "Generated by ramim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <body className="font-poppins antialiased">
        {children}
      </body>
    </html>
  );
}
